cloud:
  aws:
    region:
      auto: false
      static: eu-west-2
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

sqs:
  name: davidk-sqs